using FileHashGeneratorAndValidator.Helpers;
using FileHashGeneratorAndValidator.Models;
using System.Buffers;
using System.IO;
using System.Security.Cryptography;

namespace FileHashGeneratorAndValidator.Services
{
    public class FileHashService
    {
        public static async Task<HashOperationResult> CalculateHashAsync(
                string filePath,
                Enums.HashAlgorithm selectedAlgorithm,
                IProgress<double> progress,
                CancellationToken cancellationToken
            )
        {
            if (!File.Exists(filePath))
            {
                return new(false, "Generate hash Failed", "File not found", "");
            }

            const int bufferSize = 80 * 1024;

            var buffer = ArrayPool<byte>.Shared.Rent(bufferSize);
            long totalReadBytes = 0;
            try
            {
                using (var incrementalHash = IncrementalHash.CreateHash(AlgorithmsHelper.GetAlgorithmName(selectedAlgorithm)))
                {
                    await using (var fileStream = new FileStream(filePath, FileMode.Open, FileAccess.Read, FileShare.Read, bufferSize, FileOptions.Asynchronous | FileOptions.SequentialScan))
                    {
                        try
                        {
                            int bytesRead;

                            while ((bytesRead = await fileStream.ReadAsync(buffer.AsMemory(0, bufferSize), cancellationToken).ConfigureAwait(false)) > 0)
                            {
                                totalReadBytes += bytesRead;
                                incrementalHash.AppendData(buffer.AsSpan(0, bytesRead));
                                progress.Report(((double)totalReadBytes / fileStream.Length) * 100);
                            }

                            byte[] hashBytes = incrementalHash.GetHashAndReset();

                            return new(true, "Success", "The file hash was generated successfully", Convert.ToHexString(hashBytes.AsSpan()));
                        }
                        catch (OperationCanceledException)
                        {
                            return new(false, "Generate hash Failed", "The operation has been canceled.", "");
                        }
                    }
                }
            }
            catch (IOException ex)
            {
                return new(false, "Generate hash Failed", ex.Message, "");
            }
            catch (Exception ex)
            {
                return new(false, "Generate hash Failed", ex.Message, "");
            }
            finally
            {
                ArrayPool<byte>.Shared.Return(buffer);
            }

        }

        public static async Task<HashOperationResult> CheckAsync(
                string filePath,
                string expectedHash,
                Enums.HashAlgorithm selectedAlgorithm,
                IProgress<double> progress,
                CancellationToken cancellationToken
            )
        {
            try
            {
                if (string.IsNullOrEmpty(expectedHash))
                {
                    return new(false, "The file can't be checked.", "Please pass the expected hash", "");
                }

                if (!CheckExpectedHashLength(expectedHash, selectedAlgorithm))
                {
                    string suggestedAlgo = string.Empty;
                    var algorithms = AlgorithmsHelper.GetAlgorithmsByLength(expectedHash.Length);

                    if (algorithms.Length > 0)
                    {
                        suggestedAlgo = $"\nThe algorithms that generate this length are({string.Join(", ", algorithms)})";
                    }

                    return new(false,
                        "Algorithm Mismatch",
                        "The expected hash length doesn't match the hash length generated by the chosen algorithm. " +
                        "Please check the expected hash and the selected algorithm.\n" +
                        $"The expected hash is {expectedHash.Length} characters long, which doesn't match the chosen algorithm {selectedAlgorithm}'s length of {AlgorithmsHelper.GetAlgorithmHashLength(selectedAlgorithm)} characters." +
                        $"{suggestedAlgo}", "");
                }

                var calculateResult = await CalculateHashAsync(filePath, selectedAlgorithm, progress, cancellationToken);

                if (calculateResult.IsSuccess == false)
                    return calculateResult;

                var isValid = expectedHash.Equals(calculateResult.HashData, StringComparison.OrdinalIgnoreCase);

                string tryAnotherAlgo = string.Empty;

                if (isValid == false)
                {
                    var algorithmsWithThisLength = AlgorithmsHelper.GetAlgorithmsByLength(expectedHash.Length);

                    if (algorithmsWithThisLength.Length > 1)
                    {
                        tryAnotherAlgo = $"\nOr try the algorithm ({string.Join(",", algorithmsWithThisLength.Where(e => e != selectedAlgorithm))}) that gives the same desired length If you haven't tried it before.";
                    }
                }

                return new(isValid,
                    isValid ? "The hash was successfully verified" : "Hash verified failed",
                    isValid ?
                    "The generated hash matches the expected hash exactly." :
                    "Warning!!! The generated hash does not match the expected hash.Check the selected file and the expected hash." +
                    $"{tryAnotherAlgo}", calculateResult.HashData);
            }
            catch (Exception ex)
            {
                return new HashOperationResult(false, "Hash verified failed", ex.Message, "");
            }
            
        }

        private static bool CheckExpectedHashLength(
            string expectedHash,
            Enums.HashAlgorithm selectedAlgorith)
        {
            int algorithmHashLength = AlgorithmsHelper.GetAlgorithmHashLength(selectedAlgorith);

            return expectedHash.Length == algorithmHashLength;
        }
    }
}
