using FileHashGeneratorAndValidator.Models;
using KZ.FileHash.Engine;
using KZ.FileHash.Enums;
using KZ.FileHash.Helpers;
using System.IO;

namespace FileHashGeneratorAndValidator.Services
{
    public class FileHashService
    {
        public static async Task<HashOperationResult> CalculateHashAsync(
                string filePath,
                HashAlgorithmType selectedAlgorithm,
                IProgress<double> progress,
                CancellationToken cancellationToken
            )
        {
            try
            {
                var engine = new FileHashEngine(selectedAlgorithm);

                var hash = await engine.CalculateHashAsync(filePath, progress, cancellationToken).ConfigureAwait(false);

                return new HashOperationResult(true, "Success", "The file hash was generated successfully", hash[selectedAlgorithm]);
            }
            catch(TaskCanceledException)
            {
                return new(false, "Generate hash Failed", "The operation has been canceled.", "");
            }
            catch (OperationCanceledException)
            {
                return new(false, "Generate hash Failed", "The operation has been canceled.", "");
            }
            catch (IOException ex)
            {
                return new(false, "Generate hash Failed", ex.Message, "");
            }
            catch (Exception ex)
            {
                return new(false, "Generate hash Failed", ex.Message, "");
            }
        }

        public static async Task<HashOperationResult> CheckAsync(
                string filePath,
                string expectedHash,
                HashAlgorithmType selectedAlgorithm,
                IProgress<double> progress,
                CancellationToken cancellationToken
            )
        {
            try
            {
                if (string.IsNullOrEmpty(expectedHash))
                {
                    return new(false, "The file can't be checked.", "Please pass the expected hash", "");
                }

                if (!CheckExpectedHashLength(expectedHash, selectedAlgorithm))
                {
                    string suggestedAlgo = string.Empty;
                    var algorithms = AlgorithmsHelper.GetAlgorithmsByLength(expectedHash.Length);

                    if (algorithms.Length > 0)
                    {
                        suggestedAlgo = $"\nThe algorithms that generate this length are({string.Join(", ", algorithms)})";
                    }

                    return new(false,
                        "Algorithm Mismatch",
                        "The expected hash length doesn't match the hash length generated by the chosen algorithm. " +
                        "Please check the expected hash and the selected algorithm.\n" +
                        $"The expected hash is {expectedHash.Length} characters long, which doesn't match the chosen algorithm {selectedAlgorithm}'s length of {AlgorithmsHelper.GetAlgorithmHexStringLength(selectedAlgorithm)} characters." +
                        $"{suggestedAlgo}", "");
                }

                var calculateResult = await CalculateHashAsync(filePath, selectedAlgorithm, progress, cancellationToken);

                if (calculateResult.IsSuccess == false)
                    return calculateResult;

                var isValid = expectedHash.Equals(calculateResult.HashData, StringComparison.OrdinalIgnoreCase);

                string tryAnotherAlgo = string.Empty;

                if (isValid == false)
                {
                    var algorithmsWithThisLength = AlgorithmsHelper.GetAlgorithmsByLength(expectedHash.Length);

                    if (algorithmsWithThisLength.Length > 1)
                    {
                        tryAnotherAlgo = $"\nOr try the algorithm ({string.Join(",", algorithmsWithThisLength.Where(e => e != selectedAlgorithm))}) that gives the same desired length If you haven't tried it before.";
                    }
                }

                return new(isValid,
                    isValid ? "The hash was successfully verified" : "Hash verified failed",
                    isValid ?
                    "The generated hash matches the expected hash exactly." :
                    "Warning!!! The generated hash does not match the expected hash.Check the selected file and the expected hash." +
                    $"{tryAnotherAlgo}", calculateResult.HashData);
            }
            catch (Exception ex)
            {
                return new HashOperationResult(false, "Hash verified failed", ex.Message, "");
            }
            
        }

        private static bool CheckExpectedHashLength(
            string expectedHash,
            HashAlgorithmType selectedAlgorith)
        {
            int algorithmHashLength = AlgorithmsHelper.GetAlgorithmHexStringLength(selectedAlgorith);

            return expectedHash.Length == algorithmHashLength;
        }
    }
}
